---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[nellie]
  attributes:
    nellie:
      pkg_url: http://mirror.xmission.com/jenkins/war/1.540/jenkins.war
