---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
  driver:
  provisioner:
    name: chef_zero
    chef_omnibus_url: https://gist.github.com/fnichol/3c10e7e58625ebe63487/raw/732bee6bb97bbfabc7535357f62fc91d77e90e93/install.sh
  attributes:
    fission:
      core:
        group: yayaya
      data:
        discovery: sql
        stores:
          sql:
            type: sql

suites:
- name: fission
  run_list:
  - recipe[fission]
  - recipe[fission::data]
  - recipe[fission::data-discovery]
