---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-13.10
  driver:
    box: ubuntu-13.10
    provider: vmware_fusion
- name: macosx-10.9
  driver:
    box: macosx-10.9
    provider: vmware_fusion
    customize:
      memory: 2048
  attributes:
    nellie:
      user: vagrant
      group: admin
    java:
      dmg:
        url: http://hw-packages.s3.amazonaws.com/jdk-7u40-macosx-x64.dmg

suites:
- name: default
  run_list:
  - recipe[fission]
  attributes:
    fission:
      instances:
        nellie:
          package_url: file:///tmp/kitchen/data/nellie.jar
          config:
            options:
              fission:
                sources:
                  nellie:
                    type: test

- name: webhooks
  run_list:
  - recipe[fission]
  attributes:
    fission:
      instances:
        nellie:
          package_url: file:///tmp/kitchen/data/nellie.jar
          config:
            options:
              fission:
                branding:
                  name: hw-ops.com
                  dns: hw-ops.com
                  email: nellie@hw-ops.com
                  http: http://hw-ops.com
                  https: https://hw-ops.com
                code_fetcher:
                  github:
                    token: a_token
                github:
                  access_token: a_token
                loaders:
                  sources:
                  - carnivore-actor
                  - carnivore-http
                  - carnivore-http/point_builder
                  workers:
                  - fission-rest-api/api/github
                  - fission-rest-api
                  - fission-nellie
                  - fission-router
                  - fission-code-fetcher
                  - fission-callbacks
                  - fission-callbacks/webhooks
                rest_api:
                  github_commit:
                    job_name: router
                  setup:
                    host: 0.0.0.0
                    port: 443
                router:
                  behavior: config
                  route:
                  - nellie
                  - callbacks
                sources:
                  callbacks:
                    type: actor
                  code_fetcher:
                    type: actor
                  nellie:
                    type: actor
                  router:
                    type: actor
                utils:
                  process:
                    max_processes: 5
                    enable_spawn: true
                webhooks:
                  target: https://a_webhook
                workers:
                  callbacks_webhook: 1
                  github_commit: 1
                  router: 1
                  code_fetcher: 1
                  nellie: 1
