#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'fission', path: '.'

# cookbook 'java', git: 'https://github.com/hw-cookbooks/java.git', ref: 'macosx-dmg'
