name 'fission'
version '0.1.1'

depends 'apt'
depends 'java'
depends 'runit'
# depends 'riak'
depends 'postgresql'
depends 'vagabond'
depends 'discovery'
depends 'sudo'
depends 'gpg'
depends 'jackal'
