default[:fission][:lxd][:images] = {
 :centos_6 => 'centos/6/amd64',
 :centos_7 => 'centos/7/amd64',
 # :fedora_22 => 'fedora/22/amd64',
 # :fedora_23 => 'fedora/23/amd64',
 # :opensuse_132 => 'opensuse/13.2/amd64',
 # :oracle_6 => 'oracle/6/amd64',
 # :oracle_7 => 'oracle/7/amd64',
 # :debian_7 => 'debian/wheezy/amd64',
 # :debian_8 => 'debian/jessie/amd64',
 # :debian_testing => 'debian/stretch/amd64',
 # :debian_unstable => 'debian/sid/amd64',
 # :ubuntu_1204 => 'ubuntu/precise/amd64',
 :ubuntu_1404 => 'ubuntu/trusty/amd64',
 :ubuntu_1604 => 'ubuntu/xenial/amd64',
 # :ubuntu_1610 => 'ubuntu/yakkety/amd64'

}
default[:fission][:lxd][:packages][:centos] = ['autoconf', 'bison', 'flex', 'make', 'gcc', 'gcc-c++', 'kernel-devel', 'm4', 'patch', 'curl', 'unzip', 'zip']
default[:fission][:lxd][:packages][:default] = ['build-essential', 'curl', 'zip', 'unzip']
default[:fission][:lxd][:password] = SecureRandom.hex
default[:fission][:lxd][:image_directory] = '/opt/lxd-images'
default[:fission][:lxd][:network][:use_lxd_bridge] = true
default[:fission][:lxd][:network][:lxd_bridge] = 'lxdbr0'
default[:fission][:lxd][:network][:update_profile] = true
default[:fission][:lxd][:network][:lxd_confile] = ''
default[:fission][:lxd][:network][:lxd_domain] = 'lxd'
default[:fission][:lxd][:network][:lxd_ipv4_addr] = '10.0.8.1'
default[:fission][:lxd][:network][:lxd_ipv4_netmask] = '255.255.255.0'
default[:fission][:lxd][:network][:lxd_ipv4_dhcp_range] = '10.0.8.2,10.0.8.254'
default[:fission][:lxd][:network][:lxd_ipv4_network] = '10.0.8.0/24'
default[:fission][:lxd][:network][:lxd_ipv4_dhcp_max] = 253
default[:fission][:lxd][:network][:lxd_ipv4_nat] = true
default[:fission][:lxd][:network][:lxd_ipv6_nat] = false
default[:fission][:lxd][:network][:lxd_ipv6_proxy] = false
default[:fission][:lxd][:config][:storage_backend] = 'dir'
default[:fission][:lxd][:config][:storage_create_device] = nil
default[:fission][:lxd][:config][:storage_create_loop] = nil
default[:fission][:lxd][:config][:storage_pool] = nil
